name: LighoutBCS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-publish:
    name: CI pipeline
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MS Build
        uses: microsoft/setup-msbuild@v2

      - name: Restore Nuget Packages
        run: nuget restore LH_RnD_New.sln

      - name: Build
        run: msbuild LH_RnD_New.sln /p:Configuration=Release

      - name: Run EXE
        run: .\Lighthouse_SinglePH_BCS\bin\Release\LH_RnD_New.exe
        
      
        
      
      

  
