name: LighoutBCS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-publish:
    name: CI pipeline
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MS Build
        uses: microsoft/setup-msbuild@v2

      - name: Restore Nuget Packages
        run: nuget restore LH_RnD_New.sln

      - name: Build
        run: msbuild LH_RnD_New.sln /p:Configuration=Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-framework-winApp
          path: '**/bin/Release/'

  deploy:
      name: Deploy LH_RnD_APP
      needs: build-test-publish
      runs-on: self-hosted

      steps:
        - name: Download Build Artifact
          uses: actions/download-Artifact@v4
          with:
              name: dotnet-framework-winApp
              path: E:\LH_RnD_Deploy\Publish

        - name: Create Deployment Folder
          shell: powershell
          run: |
            $publish = "E:\LH_RnD_Deploy\Publish"
            $backup = "E:\LH_RnD_Deploy\Backup"
            $deploy = "E:\LH_RnD_Deploy\Application"

            if(!(Test-Path $publish))
            {
              New-Item -itemType Directory -Path $publish -Force | Out-Null
            }

            if(!(Test-Path $backup)){
              New-Item -itemType Directory -Path $backup -Force | Out-Null
            }
            
            if(!(Test-Path $deploy)){
              New-Item -itemType Directory -Path $deploy  -Force | Out-Null
            }

            Write-Host "Verified Folder Successfully"

        - name: Stop Application
          shell: powershell
          run: Get-Process LH_RnD_New -ErrorAction SilentlyContinue | Stop-Process -Force

        - name: Backup Current Version
          shell: powershell
          run: |
            $publish = "E:\LH_RnD_Deploy\Publish"
            $application = "E:\LH_RnD_Deploy\Application"
            $backup = "E:\LH_RnD_Deploy\Backup\$(Get-Date -Format 'yyyyMMdd_HHmmss')"

            if ((Test-Path $application) -and ((Get-ChildItem $application -Force).Count -gt 0))
            {
                Copy-Item $application -Destination $backup -Recurse -Force
                Write-Host "Backup created."
            }
            else
            {
                Write-Host "No files to backup."
            }

        - name: Clean Deploy folder
          shell: powershell
          run: |
           $deploy = "E:\LH_RnD_Deploy\Deploy"
            if(Test-Path $deploy){
              Remove-Item $deploy\* -Recurse -Force
              }

        - name: Copy New Files
          shell: powershell
          run: |
             $publish = "E:\LH_RnD_Deploy\Publish"
             $deploy = "E:\LH_RnD_Deploy\Deploy"
             Copy-Item $publish\* deploy -Recurse -Force
              


              
       

          
          
      
  

      
      
        
      
        
      
        
      
      

  
